### ISSUE TITLE
ember-template-compiler.js has sourceMappingURL at the bottom

### ISSUE THREAD

**Issue by vitch** [emberjs/emberjs-build#111]
If I `app.import('bower_components/ember/ember-template-compiler.js');` in my ember app then I get the error:

> Warning: ignoring input sourcemap for bower_components/ember/ember-template-compiler.js because ENOENT, no such file or directory

This is because the `ember-template-compiler.js` file in the [ember shim repository](https://github.com/components/ember) has `//# sourceMappingURL=ember-template-compiler.map` at the end. I presume that that file is generated by this code and put onto `builds.emberjs.com`?

I have had a look at https://github.com/emberjs/emberjs-build/tree/master/lib which I believe is probably the correct place to fix the issue but unfortunately I'm not familiar enough with it to offer a solution right now.

**Comment by rwjblue** [comment]
I'm sorry we didn't get back to this previously, but at this point this repo is unused by Ember and unmaintained.

Closing...
