### ISSUE TITLE
Upgrade core-object dependency to at least v1.1.0 to remove lodash-node deprecation warning

### ISSUE THREAD

**Issue by notmessenger** [emberjs/emberjs-build#195]
npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@^4.0.0.

```
  └─┬ ember-template-lint@0.6.4
    └─┬ glimmer-engine@0.21.2
      ├─┬ emberjs-build@0.19.0
      │ ├─┬ core-object@0.0.4
      │ │ └── lodash-node@2.4.1
```

**Comment by rwjblue** [comment]
I'm sorry we didn't get back to this previously, but at this point this repo is unused by Ember and unmaintained.

Closing...
