### ISSUE TITLE
Upgrade broccoli-string-replace to 0.1.2 to remove minimatch deprecation

### ISSUE THREAD

**Issue by notmessenger** [emberjs/emberjs-build#196]
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

```
  └─┬ ember-template-lint@0.6.4
    └─┬ glimmer-engine@0.21.2
      ├─┬ emberjs-build@0.19.0
      │ └─┬ broccoli-string-replace@0.1.1
      │   └── minimatch@2.0.10
```

**Comment by rwjblue** [comment]
I'm sorry we didn't get back to this previously, but at this point this repo is unused by Ember and unmaintained.

Closing...
